name: Build and Release Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release Go App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19' # Specify the version of Go you are using

      # Install Git tools (for tagging)
      - name: Install Git
        run: sudo apt-get install git -y

      # Determine the next version with timestamp or commit hash
      - name: Generate version with commit hash
        id: versioning
        run: |
          # Generate version based on the latest tag, commit hash, and current time
          latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          timestamp=$(date +'%Y%m%d%H%M%S')
          new_tag="${latest_tag}-${timestamp}"
          echo "New version: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      # Build the Go app for macOS (64-bit)
      - name: Build macOS binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o Infor-test-mac

      # Build the Go app for Windows (64-bit)
      - name: Build Windows 64-bit binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o Infor-test-windows.exe

      # Create a new Git tag for the version
      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      # Create a GitHub release with the new tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_tag }}
          release_name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false

      # Upload the macOS binary to the release
      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Infor-test-mac
          asset_name: Infor-test-mac
          asset_content_type: application/octet-stream

      # Upload the Windows 64-bit binary to the release
      - name: Upload Windows 64-bit binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Infor-test-windows.exe
          asset_name: Infor-test-windows.exe
          asset_content_type: application/octet-stream